// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using better_fitness_pal;

#nullable disable

namespace better_fitness_pal.Data.Migrations
{
    [DbContext(typeof(BetterFitnessPalDbContext))]
    [Migration("20260928091551_AddAuthSettingsAndDiaryTables")]
    partial class AddAuthSettingsAndDiaryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199a3c2-6b1e-7a4d-9f2e-3c5b8d7e1a01"),
                            ConcurrencyStamp = "0199a3c2-6b1e-7a4d-9f2e-3c5b8d7e1a01",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0199a3c2-6b1e-7a4d-9f2e-3c5b8d7e1a02"),
                            ConcurrencyStamp = "0199a3c2-6b1e-7a4d-9f2e-3c5b8d7e1a02",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("better_fitness_pal.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("height_cm");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Sex")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sex");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_height_cm", "height_cm BETWEEN 50 AND 300");

                            t.HasCheckConstraint("ck_users_sex", "sex IN ('male', 'female')");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.DiaryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("calories_per_100g");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("carbs_per_100g");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<decimal>("FatPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fat_per_100g");

                    b.Property<long?>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("food_name");

                    b.Property<decimal>("Grams")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("grams");

                    b.Property<short>("MealSlot")
                        .HasColumnType("smallint")
                        .HasColumnName("meal_slot");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("protein_per_100g");

                    b.Property<long?>("SavedMealId")
                        .HasColumnType("bigint")
                        .HasColumnName("saved_meal_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_diary_entries");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_diary_entries_food_id");

                    b.HasIndex("SavedMealId")
                        .HasDatabaseName("ix_diary_entries_saved_meal_id");

                    b.HasIndex("UserId", "EntryDate")
                        .HasDatabaseName("ix_diary_entries_user_id_entry_date");

                    b.ToTable("diary_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_diary_entries_calories", "calories_per_100g BETWEEN 0 AND 900");

                            t.HasCheckConstraint("ck_diary_entries_carbs", "carbs_per_100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_diary_entries_fat", "fat_per_100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_diary_entries_grams", "grams > 0");

                            t.HasCheckConstraint("ck_diary_entries_meal_slot", "meal_slot BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_diary_entries_protein", "protein_per_100g BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("calories_per_100g");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("carbs_per_100g");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("FatPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fat_per_100g");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("protein_per_100g");

                    b.Property<decimal?>("ServingSizeG")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("serving_size_g");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_foods");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_foods_barcode")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_foods_created_by_user_id");

                    b.ToTable("foods", null, t =>
                        {
                            t.HasCheckConstraint("ck_foods_barcode", "barcode ~ '^[0-9]{8,14}$'");

                            t.HasCheckConstraint("ck_foods_calories", "calories_per_100g BETWEEN 0 AND 900");

                            t.HasCheckConstraint("ck_foods_carbs", "carbs_per_100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_foods_fat", "fat_per_100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_foods_protein", "protein_per_100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_foods_serving_size_g", "serving_size_g > 0");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.SavedMeal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_meals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_meals_user_id");

                    b.ToTable("saved_meals", null, t =>
                        {
                            t.HasCheckConstraint("ck_saved_meals_name", "length(trim(name)) > 0");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.SavedMealItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<decimal>("Grams")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("grams");

                    b.Property<long>("SavedMealId")
                        .HasColumnType("bigint")
                        .HasColumnName("saved_meal_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_saved_meal_items");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_saved_meal_items_food_id");

                    b.HasIndex("SavedMealId", "FoodId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_meal_items_saved_meal_id_food_id");

                    b.ToTable("saved_meal_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_saved_meal_items_grams", "grams > 0");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("activity_level");

                    b.Property<int?>("CalorieGoal")
                        .HasColumnType("integer")
                        .HasColumnName("calorie_goal");

                    b.Property<short?>("CarbsPct")
                        .HasColumnType("smallint")
                        .HasColumnName("carbs_pct");

                    b.Property<short?>("FatPct")
                        .HasColumnType("smallint")
                        .HasColumnName("fat_pct");

                    b.Property<short?>("ProteinPct")
                        .HasColumnType("smallint")
                        .HasColumnName("protein_pct");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WeeklyGoalKg")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("weekly_goal_kg");

                    b.Property<decimal?>("WeightGoalKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_goal_kg");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("weight_unit");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_settings_activity_level", "activity_level IN ('not_very_active', 'lightly_active', 'active', 'very_active')");

                            t.HasCheckConstraint("ck_user_settings_calorie_goal", "calorie_goal > 0");

                            t.HasCheckConstraint("ck_user_settings_macro_pct_range", "protein_pct BETWEEN 0 AND 100 AND carbs_pct BETWEEN 0 AND 100 AND fat_pct BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_user_settings_macro_split", "(protein_pct IS NULL AND carbs_pct IS NULL AND fat_pct IS NULL) OR (protein_pct IS NOT NULL AND carbs_pct IS NOT NULL AND fat_pct IS NOT NULL AND protein_pct + carbs_pct + fat_pct = 100)");

                            t.HasCheckConstraint("ck_user_settings_weekly_goal_kg", "weekly_goal_kg BETWEEN -1 AND 1");

                            t.HasCheckConstraint("ck_user_settings_weight_goal_kg", "weight_goal_kg > 0");

                            t.HasCheckConstraint("ck_user_settings_weight_unit", "weight_unit IN ('kg', 'lb')");
                        });
                });

            modelBuilder.Entity("better_fitness_pal.Models.WeightEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_weight_entries");

                    b.HasIndex("UserId", "EntryDate")
                        .IsUnique()
                        .HasDatabaseName("ix_weight_entries_user_id_entry_date");

                    b.ToTable("weight_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_weight_entries_weight_kg", "weight_kg BETWEEN 20 AND 500");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.DiaryEntry", b =>
                {
                    b.HasOne("better_fitness_pal.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_diary_entries_foods_food_id");

                    b.HasOne("better_fitness_pal.Models.SavedMeal", null)
                        .WithMany()
                        .HasForeignKey("SavedMealId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_diary_entries_saved_meals_saved_meal_id");

                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diary_entries_users_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.Food", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_foods_users_created_by_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.RefreshToken", b =>
                {
                    b.HasOne("better_fitness_pal.Models.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.SavedMeal", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_meals_users_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.SavedMealItem", b =>
                {
                    b.HasOne("better_fitness_pal.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saved_meal_items_foods_food_id");

                    b.HasOne("better_fitness_pal.Models.SavedMeal", null)
                        .WithMany("Items")
                        .HasForeignKey("SavedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_meal_items_saved_meals_saved_meal_id");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("better_fitness_pal.Models.UserSettings", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("better_fitness_pal.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.WeightEntry", b =>
                {
                    b.HasOne("better_fitness_pal.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weight_entries_users_user_id");
                });

            modelBuilder.Entity("better_fitness_pal.Models.SavedMeal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
